### ISSUE TITLE
Error on launch after installing from source

### ISSUE THREAD

**Issue by JSKenyon** [ska-sa/kittens#5] opened 2018-09-27 10:20 UTC
Just did a fresh install on 18.04, cloned directly from source. I get the following after launching a meqbrowser.
```
Welcome to the MeqTrees Browser!
Please wait a second while the GUI starts up.
PyFITS package not found, rendering of FITS files will not be available.
PyFITS can be installed from the Debian/Ubuntu package python-pyfits, or can be downloaded
from http://www.stsci.edu/resources/software_hardware/pyfits.

Traceback (most recent call last):
  File "/home/jonathan/meqtrees/purr/Purr/Plugins/__init__.py", line 42, in loadPlugins
    module = imp.load_module('Purr.Plugins.%s'%modname,fp,pathname,desc);
  File "/home/jonathan/meqtrees/purr/Purr/Plugins/fits.py", line 16, in <module>
    pyfits = Kittens.utils.import_pyfits();
AttributeError: 'module' object has no attribute 'import_pyfits'
```
I definitely do have pyfits installed, but it appears that the Kittens module no longer has the import_pyfits function.

**Comment by gijzelaerr** [comment] 2018-09-27 10:58
@o-smirnov i guess this should just be removed from meqtrees also.

**Comment by gijzelaerr** [comment] 2018-12-20 14:01
duplicate of https://github.com/ska-sa/purr/issues/30

but i also added a backwards compat function in case somebody still uses this https://github.com/ska-sa/kittens/commit/01dff310389e2700bda6b7dfe84c23a337847788

**Closed by gijzelaerr** 2018-12-20 14:01 UTC
